[package]
name = "api_key_tdx"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio  ={ version="1.44", features=["macros", "fs", "rt-multi-thread", "io-util", "process", "sync"] }
axum   ={ version="0.8.4" }
clap             ={ version="4.5.37", features=["derive"] }
anyhow             ="1.0.98"
