---
name: "Build and test"
on: ["push"]

jobs:
  test:
    runs-on: core-build-runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check production mode compiles
        run: cargo check -F production

      - name: Get entropy binary from release with `master` tag
        run: |
          docker pull entropyxyz/entropy:master
          docker create --name extract-entropy-binary entropyxyz/entropy:master
          docker cp extract-entropy-binary:/usr/local/bin/entropy ./entropy
          docker container remove extract-entropy-binary

      - name: Run tests
        run: ENTROPY_NODE=$(pwd)/entropy cargo test --release
